<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Services\" />
    <Folder Include="Abstractions\Storage\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Mappings\" />
    <Folder Include="Feaures\Comments\" />
    <Folder Include="Feaures\Likes\" />
    <Folder Include="Feaures\Profiles\" />
    <Folder Include="Feaures\Users\" />
    <Folder Include="Feaures\Posts\Dtos\" />
    <Folder Include="Feaures\Posts\Validators\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeighbourhoodWatch.Domain\NeighbourhoodWatch.Domain.csproj" />
  </ItemGroup>

</Project>
