<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Identity\" />
    <Folder Include="Services\" />
    <Folder Include="Storage\" />
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeighbourhoodWatch.Application\NeighbourhoodWatch.Application.csproj" />
  </ItemGroup>

</Project>
